- src: mjanser.firewalld
- src: mjanser.powerline
- src: mjanser.ssmtp
- src: mjanser.vagrant

- src: mjanser.lets-encrypt
- src: mjanser.mysql
- src: mjanser.nginx
- src: mjanser.php
- src: mjanser.owncloud
