---
- hosts: workstations
  roles:
    - mjanser.firewalld
    - fedora-gui
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - mjanser.vagrant
    - cmprescott.chrome

- hosts: mediacenters
  roles:
    - mjanser.firewalld
    - fedora
    - mjanser.pulseaudio
    - mjanser.php
    - mjanser.nginx
    - mediacenter
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - mjanser.lets-encrypt
    - mjanser.mpd
    - mjanser.mysql
    - mjanser.cockpit
    - mjanser.owncloud
    - mjanser.mythtv
    - mjanser.kodi

- hosts: routers
  roles:
    - router
