- hosts: all
  tasks:
    - include_vars: vars.yml

- hosts: workstations
  roles:
    - fedora-workstation
    - tex
    - taxi
    - vagrant
    - php-dev

- hosts: mediacenters
  roles:
    - fedora-server
    - dbserver
