- hosts: workstations
  roles:
    - fedora-gui
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - vagrant
    - php-dev

- hosts: mediacenters
  roles:
    - fedora-server
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - dbserver
    - mediacenter
    - mpd
    - mythtv
    - kodi
    - owncloud
