- hosts: workstations
  roles:
    - fedora-gui
    - taxi
    - vagrant
    - php-dev

- hosts: mediacenters
  roles:
    - fedora-server
    - dbserver
    - mediacenter
    - mpd
    - mythtv
    - kodi
    - owncloud
