---
- hosts: workstations
  roles:
    - mjanser.firewalld
    - workstation
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - mjanser.vagrant
    - cmprescott.chrome

- hosts: mediacenters
  roles:
    - mjanser.firewalld
    - fedora-extended
    - mjanser.pulseaudio
    - mjanser.php
    - mjanser.nginx
    - mediacenter
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - mjanser.mpd
    - mjanser.mysql
    - mjanser.cockpit
    - mjanser.mythtv
    - mjanser.kodi

- hosts: cloud
  roles:
    - debian-base
    - mjanser.powerline
    - mjanser.php
    - mjanser.nginx
    - mjanser.mysql
    - mjanser.ssmtp
    - mjanser.lets-encrypt
    - mjanser.owncloud

- hosts: home-control
  roles:
    - debian-base
    - mjanser.powerline
    - mjanser.nginx
    - mjanser.ssmtp
    - home-control

- hosts: routers
  roles:
    - router
