- hosts: workstations
  roles:
    - mjanser.firewalld
    - fedora-gui
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - mjanser.vagrant

- hosts: mediacenters
  roles:
    - mjanser.firewalld
    - fedora-server
    - mjanser.gitconfig
    - mjanser.powerline
    - mjanser.tmux
    - mjanser.vim
    - mjanser.ssmtp
    - dbserver
    - mediacenter
    - mpd
    - mythtv
    - kodi
    - owncloud
