---
- hosts: workstations
  roles:
    - mjanser.firewalld
    - workstation
    - mjanser.powerline
    - mjanser.ssmtp
    - mjanser.vagrant
    - cmprescott.chrome

- hosts: cloud
  roles:
    - debian-base
    - mjanser.powerline
    - mjanser.php
    - mjanser.nginx
    - mjanser.mysql
    - mjanser.ssmtp
    - mjanser.lets-encrypt
    - mjanser.owncloud

- hosts: home-control
  roles:
    - debian-base
    - mjanser.powerline
    - mjanser.nginx
    - mjanser.ssmtp
    - home-control

- hosts: dlna
  roles:
    - debian-base
    - mjanser.powerline
    - mjanser.ssmtp
    - dlna

- hosts: routers
  roles:
    - router
