- hosts: workstations
  roles:
    - fedora-workstation
    - tex
    - taxi
    - vagrant
    - php-dev

- hosts: mediacenters
  roles:
    - fedora-server
    - dbserver
    - mediacenter
    - mpd
    - mythtv
    - kodi
    - owncloud
    - vagrant-repo-updater
