- name: ensure user 1 user exists
  user: name="{{ user1_username }}"
        comment="{{ user1_fullname }}"
        uid="{{ user1_uid }}"
        shell=/bin/bash
        password="{{ default_password }}"
        update_password=on_create
  register: user1

- name: ensure the password of user 1 user is expired
  command: "chage -d 0 {{ user1_username }}"
  when: user1.changed

- name: ensure ssh key of user 1 is added to authorized keys
  authorized_key: user="{{ user1_username }}" key="{{ user1_ssh_key }}"
