- name: ensure firewall is installed
  dnf: name={{ item }}
  with_items:
    - firewalld
    - firewall-config

- name: ensure firewalld service runs
  service: name=firewalld enabled=yes state=started

- command: firewall-cmd --get-default-zone
  register: firewalld_default_zone
  changed_when: false

- name: ensure default firewall zone is set to public
  command: firewall-cmd --set-default-zone public
  when: firewalld_default_zone.stdout != 'public'

- name: ensure ssh port is closed in public zone of firewall
  firewalld: service=ssh zone=public permanent=true state=disabled
  when: ansible_virtualization_role != 'guest'
