- name: ensure logwatch software is installed
  yum: name=logwatch

- name: ensure logwatch is configured
  copy: src=logwatch.conf
        dest=/etc/logwatch/conf/logwatch.conf
        owner=root group=root mode=0644

- name: ensure logwatch runtime configuration is installed
  copy: src=zz-runtime.conf
        dest=/etc/logwatch/conf/services/zz-runtime.conf
        owner=root group=root mode=0644
