- name: ensure php-cli software is installed
  dnf: name=php-cli

- name: ensure capifony is installed
  get_url: url=https://raw.githubusercontent.com/mjanser/capifony-docker/master/cap.sh
           dest=/usr/local/bin/cap
           force=yes
           mode=0755

- include: user.yml

- include: eclipse.yml tags=eclipse
