- name: ensure git config for developer users is installed
  template: src=git-config.j2
            dest="/home/{{ item.username }}/.gitconfig"
            owner="{{ item.username }}" group="{{ item.username }}" mode=0644
  register: git_users
  when: group_names[0] in item.hosts and item.git is defined and item.git
  with_items: users

- name: ensure gitignore directory for developer users exists
  file: dest="/home/{{ item.item.username }}/.gitignore-sources"
        state=directory
        owner="{{ item.item.username }}" group="{{ item.item.username }}" mode=0755
  when: item.item.git_ignore_github is defined or item.item.git_ignore_custom is defined
  with_items: git_users.results

- name: ensure gitignore source files from github.com for developer users are installed
  get_url: url=https://raw.githubusercontent.com/github/gitignore/master/Global/{{ item[1] }}.gitignore
           dest="/home/{{ item[0].item.username }}/.gitignore-sources/{{ item[1] }}.gitignore"
           owner="{{ item[0].item.username }}" group="{{ item[0].item.username }}" mode=0644
  with_subelements_registered:
    - git_users.results
    - git_ignore_github

- name: ensure custom gitignore source file for developer users is installed
  copy: content="{{ item.item.git_ignore.custom }}"
        dest="/home/{{ item.item.username }}/.gitignore-sources/custom.gitignore"
        owner="{{ item.item.username }}" group="{{ item.item.username }}" mode=0644
  when: item.item.git_ignore_custom is defined
  with_items: git_users.results

- name: ensure gitignore files for developer users are assembled
  assemble: src="/home/{{ item.item.username }}/.gitignore-sources"
            dest="/home/{{ item.item.username }}/.gitignore"
            owner="{{ item.item.username }}" group="{{ item.item.username }}" mode=0644
  when: item.item.git_ignore_github is defined or item.item.git_ignore_custom is defined
  with_items: git_users.results
