- name: ensure sysctl vm.swappiness is 1 for ssd optimizations
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_file: /etc/sysctl.d/40-ssd-optimizations.conf

- name: ensure sysctl vm.vfs_cache_pressure is 50 for ssd optimizations
  sysctl:
    name: vm.vfs_cache_pressure
    value: 50
    sysctl_file: /etc/sysctl.d/40-ssd-optimizations.conf

- name: ensure ssd trim timer is enabled
  service:
    name: fstrim.timer
    enabled: yes
