- name: ensure some tools are installed
  package:
    name: "{{ item }}"
  with_items:
    - iotop
    - lm_sensors
    - tlp
    - acpitool
    - powertop
    - smartmontools

- name: ensure multimedia software is installed
  package:
    name: "{{ item }}"
  with_items:
    - flac
    - ffmpeg
    - gstreamer-plugins-good
    - gstreamer-plugins-good-extras
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-bad-free-extras
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-nonfree
    - gstreamer-plugins-ugly
    - gstreamer-plugins-fc
    - gstreamer-plugin-crystalhd
    - gstreamer-rtsp
    - gstreamer-ffmpeg
    - gstreamer1-libav
    - gstreamer1-plugins-base-tools
    - gstreamer1-plugins-good
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-extras
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-ugly
    - gstreamer1-vaapi
    - lame
    - lame-libs
    - twolame-libs
    - libmatroska
    - x264
    - x264-libs
    - xvidcore
    - faac
    - faad2
    - mplayer
    - libdvdread
    - libdvdnav
    - libdvdcss
    - libva-vdpau-driver
    - libva-intel-driver
    - libva-utils
    - libexif
    - mjpegtools
    - mjpegtools-lav
    - mediainfo

- name: ensure powertop service is enabled
  service:
    name: powertop
    enabled: yes
