- name: ensure vagrant-repo-updater is installed
  git: repo=https://github.com/mjanser/vagrant-repo-updater.git
       dest=/opt/vagrant-repo-updater
       version=master

- name: ensure vagrant-repo-updater is configured
  lineinfile: dest=/opt/vagrant-repo-updater/config
              line="REMOTE={{ vagrant_repo_updater.remote }}"
              create=yes
              owner=root group=root mode=644

- name: ensure vagrant-repo-updater cron job is installed
  cron: name="vagrant-repo-updater"
        cron_file=vagrant-repo-updater
        user="{{ vagrant_repo_updater.user }}"
        minute=25
        hour=5
        job="/opt/vagrant-repo-updater/update.sh"
